### ISSUE TITLE
Cannot compile with SDK v5.6.0

### ISSUE THREAD

**Issue by Tavorcl** [BranchMetrics/android-branch-deep-linking-attribution#1071]
### Describe the bug

With the lastest SDK (5.6.0) i cannot compile my application.

Downgrading to version 5.5.0 solves the problem, but i as far as i can see, the integration instructions says that the declaration has to be with `5.+` in gradle,  instead forcing a specific version.

I also get some Dagger compilation errors which are also solved doing the downgrade. Please note that i am using kotlin v1.6.21 and i am targeting API 31

It seems that you upgraded the kotlin version but you didn't mention this in the release notes.

### Steps to reproduce

I just have try to compile the app, using the mentioned kotlin version (1.6.21)

Here is a small stack trace of the error that the compiler throws:
```
e: /root/.gradle/caches/transforms-3/88bf023c73014f5662b2a9c68b547e4f/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /root/.gradle/caches/transforms-3/88bf023c73014f5662b2a9c68b547e4f/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /root/.gradle/caches/transforms-3/88bf023c73014f5662b2a9c68b547e4f/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /root/.gradle/caches/transforms-3/a39d352e08ebee810db84fff3d7f808e/transformed/jetified-kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /root/.gradle/caches/transforms-3/baa91f324d8221206282065aed3c78f7/transformed/jetified-library-5.6.0-api.jar!/META-INF/Branch-SDK_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
Unable to watch the file system for changes. The inotify watches limit is too low.
Stopping file watching and invalidating VFS after an error happened
```

### Expected behavior

I expect the app to compile correctly

### SDK Version

5.6.0

### Make and Model

All

### OS

12

**Comment by Tavorcl** [comment]
Perhaps this the change that causes the problem:

https://github.com/BranchMetrics/android-branch-deep-linking-attribution/commit/6c0bd986f62c18e3380508f20264c1a0853b0048

**Comment by jonathanlmarsh** [comment]
I'm having the same issue. It looks like SDK 5.5.0 -> 5.6.0 updated the kotlin version from 1.6.20 to 1.8.22. We pinned the version to 5.5.0 and are able to compile again.

**Comment by gdeluna-branch** [comment]
Thanks for raising this, taking a look right now.

**Comment by gdeluna-branch** [comment]
The plan is to revert the kotlin version back to `1.6.20` https://github.com/BranchMetrics/android-branch-deep-linking-attribution/pull/1072

We will release a patch. Please use `5.5.0` in the meantime. I will close this issue once we've published. Thanks!

**Comment by gdeluna-branch** [comment]
This has been released https://central.sonatype.com/artifact/io.branch.sdk.android/library/5.6.1

Please reopen if you see anymore errors.

Thanks!
